intel/crashlog

lib/build.rs

As windows path uses backslashes as path separators, the build script has to convert the paths to use forward slashes instead.

lib: fix windows build

---

lib/src/extract/event_log.rs

This fixes the following clippy warning:
warning: this expression creates a reference which is immediately dereferenced by the compiler
--> src\extract\event_log.rs:197:40
|
197 |             match CrashLog::from_slice(&binary) {
|                                        ^^^^^^^ help: change this to: `binary`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
= note: `#[warn(clippy::needless_borrow)]` on by default
warning: redundant closure
--> src\extract\event_log.rs:213:38
|
213 |     let evtx_path_hstring = path.map(|path| HSTRING::from(path));
|                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace the closure with the function itself: `HSTRING::from`
|
= help: for further information visit …

lib: fix clippy warnings in event log extraction

---

app/src/unpack.rs

This fixes the following clippy warning:
error: this expression creates a reference which is immediately dereferenced by the compiler
--> src\unpack.rs:17:60
|
17 |     let crashlogs = CrashLog::from_windows_event_logs(Some(&evtx))
|                                                            ^^^^^ help: change this to: `evtx`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
= note: `-D clippy::needless-borrow` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::needless_borrow)]`

app: fix clippy warning in unpacking logic

---

app/Cargo.toml
efi/Cargo.toml
efi/src/args.rs
efi/src/extract.rs
efi/src/main.rs
efi/src/pager/update.rs
lib/Cargo.toml
lib/src/bert.rs
lib/src/bert/berr.rs
lib/src/collateral.rs
lib/src/collateral/embedded.rs
lib/src/collateral/target_info.rs
lib/src/crashlog.rs
lib/src/extract/efi.rs
lib/src/extract/event_log.rs
lib/src/ffi.rs
lib/src/node.rs
lib/src/record/core.rs
lib/src/region.rs
lib/tests/collateral.rs

Update Rust edition to 2024 for all the components and fix new compiler and rustfmt warnings.

Upgrade to Rust Edition 2024

---

.github/workflows/ci.yml
app/Cargo.lock
efi/Cargo.lock
lib/Cargo.toml
lib/README.md
lib/build.rs
lib/src/ffi.rs
lib/src/ffi/tests.rs

cbindgen is now added as a build dependency only when the "ffi" feature is enabled. This reduces the amount of build dependencies required to build the applications.

lib: remove ffi from default features

---

.github/workflows/docs.yml

As the FFI is now optional, the documentation must now be built with all the features enabled to include the FFI documentation.

ci: fix FFI documentation build

---

lib/src/node.rs
lib/src/record/decode.rs
lib/tests/node.rs
lib/tests/record.rs

Some decode definitions use relative paths to reference fields. This changes refactors the CSV-based decoding flow to support these cases.
This also removes the create_record_hierarchy() function from the public API.

lib: add support for relative paths in decode definitions

---

lib/tests/record.rs

Different types of invalid CSVs are now used to test the error handling flow of the decoding logic.

lib: add test cases for invalid decode definitions

---

lib/src/region.rs

When a record with an empty size is decoded, the warning message reported was rather confusing as it didn't include the type of the invalid record.

lib: improve warning message reported for empty records

---

lib/src/collateral/target_info.rs
lib/tests/collateral.rs
lib/tests/collateral/ABC/all/all/green/crashlog/target_info.json

Target info might be invalid when using customized collateral trees.

lib: improve error handling for invalid target_info

---

lib/src/error.rs
lib/src/header.rs
lib/src/record/decode.rs
lib/tests/collateral/XYZ/all/all/green/crashlog/decode-defs/MCA/all/layout.csv
lib/tests/record.rs

This allows the decode engine to look at the following path whenever a specific revision of the decode definitions could not be found:
P/V/S/S/crashlog/decode-defs/RECORD_TYPE/all/layout.csv
This change does not impact records that use type6 header.

lib: add support for generic decode definitions

---

lib/src/header.rs
lib/tests/record.rs

This patch includes the `die_skt_info` field in the Header Type6 when the header is being decode as part of the `basic_decode` flow.

lib: include `die_skt_info` in header basic decode

---

app/src/decode.rs

This patch updates the current die value shown in the `info` command. If a die name is defined in a record, the name will be shown, otherwise the die id numeric value will be shown in the info command.
For Crash Log records that don't have any die value defined, the `info` command will keep showing an empty string.

app: include die id in `info` command.

---

lib/src/collateral/target_info.rs
lib/src/header.rs
lib/tests/header.rs

This patch includes an optimization when the die id name is parsed. Instead of converting an `u8` value to `String` and then getting the name of the die from the JSON, this patch includes a `Map<u8, String>`
The header library can get the die name from this new `Map<u8, String>` and removes the need to convert the original `u8` to `String`.

lib: decode `die_id` from integer value

---

lib/src/crashlog.rs
lib/src/record/decode.rs
lib/tests/crashlog.rs
lib/tests/record.rs

This patch enables an alternative flow inside `decode`
When the current Crash Log record contains a Header Type 6 (which is the only header at the moment with `die_id` support) and there are no defined decode definitions, the current `basic_decode` function will still try to rename the die name when the header is decoded.

lib: include die name decode in `basic_decode`

---

efi/src/decode.rs
lib/README.md
lib/src/crashlog.rs
lib/src/ffi.rs
lib/src/lib.rs
lib/src/record/decode.rs

This patch is updating the current public API of the Crash Log library.
Previously there was a function in the API for decoding called `decode` which was using the collateral manager and there was another function called `basic_decode` which was not using the collateral manager.
For clarify the concepts, this patch is renaming the `basic_decode` for `decode_without_cm`, the intention is to be more precise on the usage of that function as the term "basic" is not very clear and the usage of that function is to call the decoding library in the scenario where there is no Collateral Manager available.

lib: rename `basic_decode` as `decode_without_cm`

---

app/src/main.rs

Allows the CLI to display the version of the crate:
$ iclg --version
intel_crashlog_app 0.2.0

app: add --version option

---

app/src/main.rs

The CLI command is now mandatory. This allows the help message to be displayed when no command is provided.
$ iclg
Extract and decode Intel Crash Log records.
Usage: iclg [OPTIONS] <COMMAND>
...
This change also refactors the main function to prevent the CLI from being parsed twice.

app: display help message when command is not specified

---

app/src/info.rs
app/src/main.rs

This changeset adds a markdown format for the info command. Right now, two formats are supported - 'compact' and 'markdown'.
Usage:
$ iclg info --format markdown sample.crashlog

app: add markdown format for the info command

---

lib/src/crashlog.rs
lib/src/error.rs
lib/src/region.rs
lib/tests/region.rs

The box record payload does not always contain data. Checking if the region is empty during its construction prevents the invalid box payload to appear in the region list stored in the Crash Log struct.
This also prevents the unpack command to report empty regions and the decode function to consider empty files as valid.
$ touch empty.crashlog
$ iclg decode empty.crashlog
Fatal Error: The Crash Log Region is not populated

lib: handle empty regions

---

app/src/extract.rs
lib/src/crashlog.rs
lib/src/extract/efi.rs
lib/src/extract/event_log.rs
lib/src/extract/sysfs.rs
lib/src/ffi.rs

The Crash Log regions that are exposed by Intel PMT are accessible through the linux sysfs.
The linux extraction function implemented in the library is being updated to look for any valid records that can be found in the ACPI tables and PMT structures.

lib: add support for extraction from intel_pmt sysfs

---

lib/src/crashlog.rs
lib/src/header.rs
lib/src/record.rs
lib/src/record/decode.rs
lib/src/region.rs
lib/tests/crashlog.rs

In situations where there is a `Box` Record with a HeaderType 6, the records that are inside of the `Box` should inherit the socket and die name in the case that they don't have any socket or die defined.
As it is valid that the records inside of the `Box` may have a different `ProductID` than the `Box` itself, the intention is that the records in the Box can inherit the name of the die and socket id of the box and the name comes directly from the product collateral.
In this patch the current behaviour of the decoder of the records inside the Box will change, and in case those records don't have any `die` name defined, the decoder will check if the `Box` record has a die name defined and will use it in the `root_node` hierarchy.

lib: include `parent_header` in current `Record` context.

---

lib/collateral/SRF/SP/all/all/crashlog/target_info.json

This patch includes the target info file in the collateral tree for `SRF` product.

lib: include `SRF-SP` target info in collateral

---

lib/collateral/CMT/all/all/all/crashlog/target_info.json

This patch includes the crestmont target_info.json file, needed to recognize Crash Log records coming from `CMT` products.

collateral: include `CMT` target_info file
